export const AGREEMENT_SCALE = [
  { value: "1", label: "Strongly disagree" },
  { value: "2", label: "Disagree" },
  { value: "3", label: "Neither" },
  { value: "4", label: "Agree" },
  { value: "5", label: "Strongly agree" },
];

export const FREQUENCY_SCALE = [
  { value: "1", label: "Never" },
  { value: "2", label: "Rarely" },
  { value: "3", label: "Sometimes" },
  { value: "4", label: "Often" },
  { value: "5", label: "Almost always" },
];

export const IMPORTANCE_SCALE = [
  { value: "1", label: "Not at all" },
  { value: "2", label: "Slightly" },
  { value: "3", label: "Moderately" },
  { value: "4", label: "Very" },
  { value: "5", label: "Essential" },
];

export const RESEARCH_STAGES = [
  "Literature search & synthesis",
  "Hypothesis / research-question generation",
  "Experiment / study design",
  "Setup & implementation (code, apparatus, protocols)",
  "Execution (running experiments, simulations, instruments)",
  "Data processing & analysis",
  "Interpretation & validation of results",
  "Writing & communication",
];

const TOOL_ACTIVITIES = [
  "physical",
  "simulation",
  "data_analysis",
  "formal_computation",
  "automated_workflow",
  "other_tool",
];

const COMPUTATIONAL_ACTIVITIES = ["simulation", "data_analysis", "formal_computation"];

export const sections = [
  {
    id: "welcome",
    code: "00",
    shortTitle: "Welcome",
    title: "Welcome & consent",
    introTitle: "Scientific Workflows & AI Agents",
    intro:
      "We are building University of Scientific Workflow (USW), a public benchmark that evaluates whether AI agents can carry out real scientific research workflows. This survey asks how working scientists define problems, use tools, adapt workflows, and decide whether results are trustworthy.",
    bullets: ["About 15 minutes", "Nine short parts", "Identity used only for eligibility", "Results reported in aggregate"],
    questions: [
      {
        type: "info",
        tone: "accent",
        title: "Who this survey is for",
        paragraphs: [
          "We are looking for working scientists in the natural sciences. You are eligible if you are a Ph.D. student, postdoctoral researcher, research or staff scientist, or professor with at least one peer-reviewed publication in an archival journal or conference (workshop papers excluded).",
          "Computer-science and AI researchers are included if their undergraduate degree was in a natural science or they substantially use computational or AI methods to address natural-science questions.",
        ],
      },
      {
        type: "info",
        title: "Consent & data use",
        bullets: [
          "Participation is voluntary; you may skip optional questions or stop at any time.",
          "Name, institutional email, and ORCID or Google Scholar profile are collected only for eligibility and optional follow-up.",
          "Identity data will be stored separately from analysis data and will not be published.",
          "This page is a technical prototype. Institutional review information must be added before broad distribution.",
        ],
      },
      {
        id: "CONSENT",
        type: "checkboxes",
        prompt: "Please confirm before continuing.",
        required: true,
        options: [
          {
            value: "consent",
            label: "I have read the information above, am at least 18 years old, and voluntarily wish to continue.",
          },
        ],
      },
    ],
  },
  {
    id: "screening",
    code: "S",
    shortTitle: "Screening",
    title: "Screening",
    introTitle: "Who is eligible for this round",
    intro: "These questions confirm eligibility and help us describe the scientific community represented in the study.",
    questions: [
      {
        id: "S1",
        type: "radio",
        prompt: "Which best describes your current position?",
        required: true,
        options: [
          "Ph.D. student",
          "Postdoctoral researcher",
          "Research scientist / staff scientist (university, national lab, or industry)",
          "Professor (assistant / associate / full)",
          { value: "Other", label: "Other", other: true },
        ],
      },
      {
        id: "S2",
        type: "radio",
        prompt: "What is your primary research field?",
        required: true,
        options: [
          "Physics",
          "Chemistry",
          "Biology / life sciences",
          "Materials science & engineering",
          "Earth / environmental / climate science",
          "Astronomy / astrophysics",
          "Neuroscience",
          "Medicine / biomedical science",
          "Mathematics / applied mathematics",
          "Computer science / AI",
          "Engineering (other)",
          { value: "Other", label: "Other", other: true },
        ],
      },
      {
        id: "S2a",
        type: "text",
        prompt: "Sub-field, in a few words",
        help: "For example: computational catalysis, soft-matter physics, or observational cosmology.",
        required: true,
        placeholder: "Your sub-field",
      },
      {
        id: "S3",
        type: "radio",
        prompt:
          "Does your research primarily use computational or AI methods to address questions in the natural sciences, and/or was your undergraduate degree in a natural science?",
        required: true,
        options: ["Yes", "No"],
        showIf: { question: "S2", equals: "Computer science / AI" },
      },
      {
        id: "S4",
        type: "radio",
        prompt:
          "How many peer-reviewed publications do you have in archival journals or conference proceedings (excluding workshop papers)?",
        required: true,
        options: ["0", "1–2", "3–5", "6–10", "11–30", "More than 30"],
      },
      {
        id: "S5",
        type: "radio",
        prompt: "Which statement best describes your experience leading a research project?",
        required: true,
        options: [
          "No project-lead experience yet",
          "Led a research study that resulted in a first-author publication",
          "Led a sub-project",
          "PI or co-PI of a funded project",
          "Led a large multi-investigator or multi-institution project",
        ],
      },
    ],
  },
  {
    id: "profile",
    code: "A",
    shortTitle: "Profile",
    title: "Researcher profile",
    introTitle: "Identity and research experience",
    intro:
      "Identity information is used only for eligibility verification and optional follow-up. It should be stored separately from analysis data in the production system.",
    questions: [
      {
        id: "A1",
        type: "text",
        prompt: "Name (first / last)",
        help: "Used only for eligibility verification and optional follow-up. Never published.",
        required: true,
        autocomplete: "name",
        placeholder: "First and last name",
      },
      {
        id: "A2",
        type: "email",
        prompt: "Institutional email address",
        help: "Please use your current institution's domain; personal webmail addresses are not accepted.",
        required: true,
        autocomplete: "email",
        placeholder: "name@institution.edu",
        institutionalEmail: true,
      },
      {
        id: "A3",
        type: "fields",
        prompt: "Institution and country of institution",
        required: true,
        fields: [
          { key: "institution", label: "Institution", placeholder: "University, national lab, or company" },
          { key: "country", label: "Country", placeholder: "Country" },
        ],
      },
      {
        id: "A4",
        type: "url",
        prompt: "ORCID iD or Google Scholar profile URL",
        help: "We verify publication records from this profile instead of asking you to list papers.",
        required: true,
        placeholder: "https://orcid.org/... or Google Scholar URL",
      },
      {
        id: "A5",
        type: "url",
        prompt: "GitHub profile or personal homepage",
        required: false,
        placeholder: "https://...",
      },
      {
        id: "A6",
        type: "radio",
        prompt: "Years of research experience since your first peer-reviewed publication",
        required: true,
        options: ["Less than 2", "2–5", "6–10", "11–20", "More than 20"],
      },
      {
        id: "A7",
        type: "radio",
        prompt: "Have you served as a peer reviewer for journals or conferences?",
        required: true,
        options: ["No", "Occasionally (1–10)", "Regularly (11–50)", "Extensively (50+)"],
      },
      {
        id: "A7a",
        type: "text",
        prompt: "Main venues reviewed for",
        required: false,
        placeholder: "Optional",
        showIf: { question: "A7", notEquals: "No" },
      },
      {
        id: "A8",
        type: "radio",
        prompt: "Have you received a paper award (best / outstanding / runner-up)?",
        required: true,
        options: ["No", "Yes"],
      },
      {
        id: "A8a",
        type: "text",
        prompt: "Award venue(s) and year(s)",
        required: true,
        placeholder: "Venue and year",
        showIf: { question: "A8", equals: "Yes" },
      },
    ],
  },
  {
    id: "goals",
    code: "B",
    shortTitle: "Goals",
    title: "Research goals, questions & approaches",
    introTitle: "Think about your current or most recent main project",
    intro:
      "There are no better or worse answers. For B1, think about your research overall. For B2–B4, use your current or most recent main research project as the reference.",
    questions: [
      {
        id: "B1a",
        type: "likert",
        prompt: "A major goal of my research is to advance fundamental understanding.",
        required: true,
        options: AGREEMENT_SCALE,
      },
      {
        id: "B1b",
        type: "likert",
        prompt: "A major goal of my research is to address practical needs or applications.",
        required: true,
        options: AGREEMENT_SCALE,
      },
      {
        id: "B2a",
        type: "checkboxes",
        prompt: "Which descriptions apply to the main research question or objective of your project?",
        help: "Select all that apply.",
        required: true,
        options: [
          "A well-established research question; we aimed to improve, refine, or extend existing approaches",
          "A new or underexplored research question or direction",
          "An unexpected observation or result that remained inadequately explained after known factors and standard explanations were considered",
          "A widely recognized open problem or grand challenge in my field",
          "A practical need arising in a real-world setting",
          { value: "Other", label: "Other", other: true },
        ],
      },
      {
        id: "B2b",
        type: "checkboxes",
        prompt: "What type of contribution was your project mainly intended to make?",
        help: "Select all that apply.",
        required: true,
        options: [
          "An empirical discovery, measurement, or characterization",
          "A new or improved explanation, predictive model, or theory",
          "A formal theoretical or mathematical result, such as a proof",
          "A practical solution, design, or intervention",
          "A new or improved method, protocol, instrument, software package, dataset, benchmark, or other research tool",
          { value: "Other", label: "Other", other: true },
        ],
      },
      {
        id: "B3",
        type: "constantSum",
        prompt: "Over the past 12 months, approximately what percentage of your research effort was spent in each mode?",
        help:
          "Classify an activity by its primary purpose, not simply by whether software was used. The total must add up to 100%.",
        required: true,
        items: [
          { key: "experimental", label: "Experimental / observational work involving physical or biological systems" },
          { key: "theoretical", label: "Theoretical / formal analytical work" },
          { key: "simulation", label: "Computational modeling & simulation of systems or processes" },
          { key: "analysis", label: "Data processing, analysis, and interpretation" },
        ],
      },
      {
        id: "B4a",
        type: "textarea",
        prompt:
          "Identify one or more specific research questions or technical challenges in your subfield that are currently especially difficult to solve or make progress on.",
        help: "For each item, provide a brief explanation in 1–2 sentences and enter it on a separate line.",
        required: true,
        rows: 5,
      },
      {
        id: "B4b",
        type: "textarea",
        prompt:
          "Identify one or more emerging research questions or directions in your subfield that you expect to lead to important advances over the next 10 years.",
        help: "For each item, provide a brief explanation in 1–2 sentences and enter it on a separate line.",
        required: true,
        rows: 5,
      },
    ],
  },
  {
    id: "tools",
    code: "C",
    shortTitle: "Tools",
    title: "Tools, instruments, simulation & automation",
    introTitle: "What your results depend on",
    intro:
      "Think about the instruments, software, simulations, and automated systems used in your current or most recent main research project.",
    questions: [
      {
        id: "C1",
        type: "checkboxes",
        prompt: "Which activities were required to produce or validate the project's main results?",
        help: "Select all that apply.",
        required: true,
        exclusiveValue: "none",
        options: [
          { value: "physical", label: "Conducting physical experiments or collecting observations or measurements using instruments or equipment" },
          { value: "simulation", label: "Running computational models or simulations" },
          { value: "data_analysis", label: "Processing, analyzing, or visualizing data using software or code" },
          { value: "formal_computation", label: "Performing theoretical, symbolic, or formal calculations using specialized software" },
          { value: "automated_workflow", label: "Operating an automated workflow that connects multiple instruments or software tools" },
          { value: "other_tool", label: "Other tool-based research activity", other: true },
          { value: "none", label: "None of the above" },
        ],
      },
      {
        id: "C2",
        type: "toolRepeater",
        prompt: "Which tools were central to producing or validating the project's main results?",
        help:
          "Include instruments, equipment, software packages, codebases, and workflow systems. Add one entry for each central tool; general office software need not be included.",
        required: true,
        showIf: { question: "C1", includesAny: TOOL_ACTIVITIES },
      },
      {
        id: "C3a",
        type: "radio",
        prompt:
          "After your primary instrument or experimental system is started, how much work can it typically complete before a researcher must intervene?",
        required: true,
        options: [
          "It requires intervention before completing one full run or measurement",
          "It can complete one full run or measurement",
          "It can process multiple samples, runs, or measurements as a batch",
          "It can operate continuously",
          "This varies too widely to estimate",
          "Not sure or not applicable",
        ],
        showIf: { question: "C1", includes: "physical" },
      },
      {
        id: "C3a_detail",
        type: "text",
        prompt: "Approximately how many samples/runs, or for how long?",
        required: true,
        placeholder: "For example: 24 samples or 8 hours",
        showIf: {
          question: "C3a",
          in: ["It can process multiple samples, runs, or measurements as a batch", "It can operate continuously"],
        },
      },
      {
        id: "C3b",
        type: "checkboxes",
        prompt: "Which parts of the process can the instrument or experimental system perform automatically?",
        help: "Select all that apply.",
        required: true,
        exclusiveValue: "None of these",
        options: [
          "Loading or positioning samples or specimens",
          "Calibration or setup",
          "Setting operating parameters or experimental conditions",
          "Running the experiment or collecting data",
          "Monitoring quality or detecting errors",
          "Recovering from errors or repeating failed measurements",
          "None of these",
          { value: "Other", label: "Other", other: true },
        ],
        showIf: { question: "C1", includes: "physical" },
      },
      {
        id: "C3c",
        type: "radio",
        prompt: "What is the highest level of data processing completed automatically before a researcher first reviews the output?",
        required: true,
        options: [
          "No automatic processing; the researcher receives raw data",
          "Basic processing, such as calibration, correction, cleaning, or file conversion",
          "Feature extraction, curve fitting, or quantitative measurement",
          "Statistical summaries or visualizations",
          "Preliminary classification or interpretation",
          "This varies by instrument or experiment",
          "Not sure or not applicable",
        ],
        showIf: { question: "C1", includes: "physical" },
      },
      {
        id: "C3d",
        type: "radio",
        prompt: "Can custom software control the instrument or retrieve its data without a person operating the human-facing interface?",
        required: true,
        options: [
          "Yes, through a documented API or SDK",
          "Yes, through a command-line interface, script, or macro",
          "Data can be transferred automatically, but the instrument itself cannot be controlled programmatically",
          "No; operation requires a graphical interface or physical controls",
          "Not sure",
        ],
        showIf: { question: "C1", includes: "physical" },
      },
      {
        id: "C4a",
        type: "matrix",
        prompt: "For each computational activity used in the project, how automated is the typical workflow?",
        required: true,
        columns: [
          { value: "manual", label: "Mostly manual or interactive" },
          { value: "some_scripted", label: "Some steps scripted; major handoffs manual" },
          { value: "mostly_scripted", label: "Most steps automated; researcher starts and reviews each run" },
          { value: "unattended", label: "Input-to-output without intervention" },
          { value: "adaptive", label: "Adaptive or closed-loop" },
        ],
        rows: [
          { key: "simulation", label: "Modeling or simulation", showIf: { question: "C1", includes: "simulation" } },
          { key: "data_analysis", label: "Data processing or analysis", showIf: { question: "C1", includes: "data_analysis" } },
          { key: "formal_computation", label: "Theoretical or formal computation", showIf: { question: "C1", includes: "formal_computation" } },
        ],
        showIf: { question: "C1", includesAny: COMPUTATIONAL_ACTIVITIES },
      },
      {
        id: "C4b",
        type: "text",
        prompt: "If software automatically coordinates and runs multiple steps, what software do you use?",
        help: "Enter the software name or “custom/lab-built.” Leave blank if not applicable.",
        required: false,
        showIf: { question: "C1", includesAny: COMPUTATIONAL_ACTIVITIES },
      },
      {
        id: "C5",
        type: "radio",
        prompt: "How are data, inputs, and results transferred between the main tools in this workflow?",
        required: true,
        options: [
          "Information is manually re-entered or copied between tools",
          "Files are manually exported and imported",
          "Scripts automate some transfers, but major handoffs are manual",
          "Most transfers are automated, with human review at specific checkpoints",
          "The tools are connected in an end-to-end automated workflow",
          "Only one main tool is used",
          "Not sure or not applicable",
        ],
        showIf: { question: "C1", includesAny: TOOL_ACTIVITIES },
      },
      {
        id: "C6",
        type: "textarea",
        prompt: "Which step in this workflow currently requires the most hands-on operation or scientific judgment?",
        help: "Briefly describe what the researcher must do in 1–2 sentences.",
        required: true,
        rows: 3,
        showIf: { question: "C1", includesAny: TOOL_ACTIVITIES },
      },
      {
        type: "info",
        title: "Documentation and reproducibility",
        paragraphs: [
          "For the next questions, assume that a competent Ph.D. student in your field has access to the same inputs, materials, equipment, software, and computing resources.",
        ],
      },
      {
        id: "C7a",
        type: "radio",
        prompt: "Using only your existing documentation and workflow records, how much of the workflow could they execute correctly without contacting you?",
        required: true,
        options: [
          "All steps, without clarification",
          "Most steps, with only minor clarification or guesswork",
          "Some steps, but substantial clarification or tacit knowledge would be required",
          "Few or none of the steps",
          "Not sure",
        ],
      },
      {
        id: "C7b",
        type: "radio",
        prompt: "If the student executed the workflow correctly, would you expect sufficiently similar results to support the same main scientific conclusion?",
        help: "Sufficiently similar means within a tolerance appropriate to your field; every intermediate value need not be identical.",
        required: true,
        options: ["Definitely yes", "Probably yes", "Unsure", "Probably no", "Definitely no", "Not applicable"],
      },
      {
        id: "C7c",
        type: "checkboxes",
        prompt: "In practice, which factors could make the workflow or result difficult to reproduce?",
        help: "Select all that apply.",
        required: true,
        exclusiveValue: "None of the above",
        options: [
          "Missing, incomplete, or unclear documentation",
          "Unavailable data, samples, materials, or other inputs",
          "Limited access to equipment, facilities, or proprietary software",
          "Software, hardware, version, or computing-environment differences",
          "Randomness, measurement uncertainty, or sample variability",
          "Tacit skills or scientific judgment that are difficult to document",
          "Analysis or interpretation steps that have not been fully specified or independently validated",
          { value: "Other", label: "Other", other: true },
          "None of the above",
        ],
      },
    ],
  },
  {
    id: "workflows",
    code: "D",
    shortTitle: "Workflows",
    title: "How you work — scientific workflows",
    introTitle: "Planning, adapting, validating & documenting",
    intro:
      "A research workflow is the sequence of activities used to move from a research question or objective to a sufficiently supported result. It may be linear, iterative, or branching, and may include physical experiments, observations, calculations, simulations, analysis, and interpretation.",
    questions: [
      {
        id: "D0",
        type: "workflow",
        prompt: "Outline the main stages of your current or most recent main research project, from the initial question or objective to the main result or conclusion.",
        help:
          "A high-level outline is sufficient. Click a block to name it, drag its grip to arrange it, and connect blocks with flow, branch, or loop arrows. Use a loop when the process revisited an earlier stage. Do not disclose confidential details.",
        example:
          "Research question → material synthesis → spectroscopy measurement → data processing → structure analysis → [if needed: adjust settings ↺ repeat measurement and analysis] → validation → interpretation",
        required: true,
      },
      {
        id: "D1",
        type: "radio",
        prompt: "At the start of this project, how much of the research process was planned in advance?",
        required: true,
        options: [
          "Most steps and major decision points were specified in advance",
          "The major stages were planned, but the details were determined later",
          "Only the initial steps were planned; later steps depended on intermediate results",
          "Little or no sequence was planned in advance",
        ],
      },
      {
        id: "D2",
        type: "radio",
        prompt: "Which description best matches how the project usually progressed?",
        required: true,
        options: [
          "Mostly as a fixed sequence of steps",
          "Through fixed major stages, with flexibility in the methods used within each stage",
          "Through different branches depending on intermediate results",
          "Through repeated cycles that revisited and refined earlier steps",
          "Mostly through exploration, without a stable sequence of steps",
          { value: "Other", label: "Other", other: true },
        ],
      },
      {
        id: "D3",
        type: "likert",
        prompt: "How often did intermediate results cause you to change what you did next?",
        required: true,
        options: FREQUENCY_SCALE,
      },
      {
        id: "D3a",
        type: "checkboxes",
        prompt: "When the research process changed, what usually changed?",
        help: "Select all that apply.",
        required: true,
        options: [
          "The research question, hypothesis, or objective",
          "The overall strategy or order of steps",
          "The method, tool, or instrument used within a step",
          "Parameters, settings, or experimental conditions",
          "The criteria used to evaluate or validate a result",
          "The decision to repeat, stop, or abandon part of the work",
          { value: "Other", label: "Other", other: true },
        ],
        showIf: { question: "D3", numericAtLeast: 3 },
      },
      {
        id: "D4",
        type: "likert",
        prompt: "To what extent could this project be divided into distinct steps, each with a clear purpose and an identifiable output?",
        required: true,
        options: [
          { value: "1", label: "Not at all" },
          { value: "2", label: "Slightly" },
          { value: "3", label: "Moderately" },
          { value: "4", label: "Mostly" },
          { value: "5", label: "Completely" },
        ],
      },
      {
        id: "D5",
        type: "radio",
        prompt: "For roughly what fraction of those steps could a qualified researcher determine whether the output was acceptable before moving on?",
        help:
          "An output may be checked using a quantitative threshold, formal verification, a benchmark or reference, or a clearly stated qualitative criterion.",
        required: true,
        options: ["Almost none", "Less than half", "About half", "More than half", "Almost all"],
      },
      {
        id: "D6a",
        type: "checkboxes",
        prompt: "How did you check that the workflow, or individual steps within it, were working as intended?",
        help: "Select all that apply.",
        required: true,
        options: [
          "Compared the result with a known, published, or previously validated result",
          "Tested the workflow on a simple case whose answer could be checked independently",
          "Used calibration samples, reference standards, or positive or negative controls",
          "Repeated the experiment, calculation, or analysis",
          "Performed convergence, sensitivity, or robustness checks",
          "Used automated tests for code or data-processing steps",
          "Used formal verification or a proof-checking system",
          "Compared results produced by a different method, tool, or implementation",
          "Inspected the result using expert scientific judgment",
          "Checked whether the result was consistent with physical constraints or other downstream evidence",
          "I did not routinely perform a separate check",
          { value: "Other", label: "Other", other: true },
        ],
      },
      {
        id: "D6b",
        type: "textarea",
        prompt: "Describe one concrete example of how you verified or evaluated the workflow, or one of its steps.",
        help: "What did you check, how did you check it, and what result would have indicated a problem? Write 2–3 sentences.",
        example:
          "Examples include checking a proof with a formal verifier, testing a simulation against a known simple case, running an analysis pipeline on synthetic data, or using a calibration sample or control experiment.",
        required: true,
        rows: 4,
      },
      {
        id: "D7",
        type: "likert",
        prompt: "Before running a key step, how often did you state in advance what result would count as acceptable or indicate a problem?",
        required: true,
        options: FREQUENCY_SCALE,
      },
      {
        id: "D8",
        type: "checkboxes",
        prompt: "What records did you keep while the project was underway?",
        help: "Select all that apply.",
        required: true,
        options: [
          "Memory or ad hoc notes",
          "Paper or electronic lab notebook",
          "Written protocols or README files",
          "Input values, parameters, or experimental conditions",
          "Instrument, software, package, or computing-environment versions",
          "Version-controlled code and scripts",
          "Raw, intermediate, or final outputs",
          "Decisions and the reasons for making them",
          "Failed attempts, deviations, or troubleshooting steps",
          "Workflow or pipeline definitions",
          { value: "Other", label: "Other", other: true },
        ],
      },
    ],
  },
  {
    id: "ai",
    code: "E",
    shortTitle: "AI experience",
    title: "AI agents — experience & attitudes",
    introTitle: "Your hands-on experience and view of usefulness",
    intro:
      "By AI agent we mean an AI system that can autonomously carry out multi-step tasks—planning, using tools, and iterating on results—beyond single-turn chat. Examples include Claude Code, OpenAI Codex or ChatGPT agent mode, Gemini CLI, GitHub Copilot agent mode, OpenHands, and lab-built systems.",
    questions: [
      {
        id: "E1",
        type: "radio",
        prompt: "How familiar are you with AI agents?",
        required: true,
        options: [
          { value: "never_heard", label: "Never heard of them before this survey" },
          { value: "aware", label: "Aware, but never used one" },
          { value: "tried", label: "Tried one a few times" },
          { value: "monthly", label: "Use one occasionally (about monthly)" },
          { value: "weekly", label: "Use one regularly (weekly or more)" },
        ],
      },
      {
        id: "E2",
        type: "likert",
        prompt: "How interested are you in using AI agents in your research?",
        required: true,
        options: [
          { value: "1", label: "Not at all" },
          { value: "2", label: "Slightly" },
          { value: "3", label: "Moderately" },
          { value: "4", label: "Very" },
          { value: "5", label: "Extremely" },
        ],
      },
      {
        id: "E2a",
        type: "text",
        prompt: "Why?",
        help: "Optional, one line.",
        required: false,
      },
      {
        id: "E3",
        type: "checkboxes",
        prompt: "Which AI agents have you used?",
        help: "Select all that apply.",
        required: true,
        options: [
          "Claude Code",
          "OpenAI Codex / ChatGPT agent mode",
          "Gemini CLI",
          "GitHub Copilot (agent mode)",
          "OpenHands",
          "Custom / lab-built",
          { value: "Other", label: "Other", other: true },
        ],
        showIf: { question: "E1", in: ["tried", "monthly", "weekly"] },
      },
      {
        id: "E3a",
        type: "radio",
        prompt: "How is your AI-agent access paid for?",
        required: true,
        options: ["Free tiers only", "Personal subscription", "Lab or institutional license"],
        showIf: { question: "E1", in: ["tried", "monthly", "weekly"] },
      },
      {
        id: "E4",
        type: "checkboxes",
        prompt: "What have you used AI agents for?",
        help: "Select all that apply.",
        required: true,
        options: [
          "Literature search & synthesis",
          "Writing or editing manuscripts, including translation",
          "Writing research code",
          "Debugging / refactoring code",
          "Brainstorming experiment or analysis designs",
          "Running simulations / tools autonomously",
          "Data processing & analysis",
          "Managing multi-step pipelines",
          { value: "Other", label: "Other", other: true },
        ],
        showIf: { question: "E1", in: ["tried", "monthly", "weekly"] },
      },
      {
        id: "E5",
        type: "checkboxes",
        prompt: "Have you used any advanced agent features?",
        required: true,
        exclusiveValue: "None",
        options: ["None", "MCP servers / tool connectors", "Skills / plugins", "Hooks / automations", "Custom scaffolding or scripts around an agent"],
        showIf: { question: "E1", in: ["tried", "monthly", "weekly"] },
      },
      {
        id: "E5a",
        type: "text",
        prompt: "For what purpose did you use those advanced features?",
        required: false,
        showIf: { question: "E5", hasAnyExcept: "None" },
      },
      {
        id: "E6",
        type: "radio",
        prompt: "Has an AI agent ever executed part of your actual research workflow end-to-end, rather than only assisting interactively?",
        required: true,
        options: ["No", "Yes, once or twice", "Yes, routinely"],
        showIf: { question: "E1", in: ["tried", "monthly", "weekly"] },
      },
      {
        id: "E6a",
        type: "text",
        prompt: "Which part of the workflow?",
        required: true,
        showIf: { question: "E6", in: ["Yes, once or twice", "Yes, routinely"] },
      },
      {
        id: "E7",
        type: "matrix",
        prompt: "Rate your agreement with each statement.",
        required: true,
        columns: AGREEMENT_SCALE,
        rows: [
          { key: "productivity", label: "Using AI agents would improve my research productivity." },
          { key: "quality", label: "Using AI agents would improve the quality or rigor of my science." },
          { key: "ease", label: "Learning to make AI agents work for my research would be easy for me." },
          { key: "intent", label: "I intend to use AI agents in my research within the next 12 months." },
        ],
      },
      {
        id: "E8",
        type: "likert",
        prompt:
          "Before relying on a research result produced by an AI agent, I would need to personally inspect every major intermediate output—not just the final result.",
        help: "Intermediate outputs may include processed data, calculations or proof steps, code outputs, or experimental decisions.",
        required: true,
        options: AGREEMENT_SCALE,
      },
      {
        id: "E8a",
        type: "textarea",
        prompt: "What would this checking typically involve in your research?",
        help: "Optionally describe which intermediate outputs you would inspect and how, in 1–2 sentences.",
        required: false,
        rows: 3,
      },
    ],
  },
  {
    id: "benchmark",
    code: "F",
    shortTitle: "Benchmark",
    title: "AI agents in your research & benchmark feedback",
    introTitle: "Where you would let an agent in",
    intro: "Tell us which research stages you would delegate, where you would retain control, and how USW should evaluate scientifically valid work.",
    questions: [
      {
        id: "F1",
        type: "matrix",
        prompt: "For each research stage, choose one role for an AI agent in your own research.",
        required: true,
        columns: [
          { value: "delegate", label: "Delegate fully" },
          { value: "checkpoint", label: "Delegate with checkpoint review" },
          { value: "assist", label: "AI assists; I lead" },
          { value: "no_ai", label: "Would not use AI here" },
          { value: "na", label: "N/A" },
        ],
        rows: RESEARCH_STAGES.map((label, index) => ({ key: `stage_${index + 1}`, label })),
      },
      {
        id: "F2",
        type: "radio",
        prompt: "Which single stage above currently consumes the most of your working time?",
        required: true,
        options: RESEARCH_STAGES,
      },
      {
        id: "F3",
        type: "textarea",
        prompt: "Describe one concrete task from your own research that you would most want to hand to an AI agent.",
        help: "What is the task, why this one, and what measurable improvement would you expect? Write 3–5 sentences.",
        required: true,
        rows: 6,
      },
      {
        id: "F3b",
        type: "radio",
        prompt: "If an AI agent handled that task well, what would be the primary benefit?",
        required: true,
        options: [
          "Faster results",
          "Larger scale (more conditions / samples tested)",
          "Fewer errors, more rigor",
          "Ideas or designs I would not have produced",
          "Access to methods or tools I cannot currently operate",
          "Freeing my time for higher-level thinking",
        ],
      },
      {
        id: "F4",
        type: "text",
        prompt: "In the next 5–10 years, what type of scientific problem could AI agents contribute to most significantly?",
        required: true,
      },
      {
        type: "info",
        tone: "accent",
        title: "About the benchmark",
        paragraphs: [
          "University of Scientific Workflow evaluates AI agents by having them execute real or potential workflows decomposed into atomic steps. Each step is verified against targets set by the original scientists. Agents are scored on step achievement, final task completion, and workflow fidelity—not only the final answer.",
        ],
      },
      {
        id: "F5a",
        type: "likert",
        prompt: "Evaluating agents on faithful step-by-step execution of real workflows is a meaningful measure of scientific capability.",
        required: true,
        options: AGREEMENT_SCALE,
      },
      {
        id: "F5b",
        type: "text",
        prompt: "Why or why not?",
        required: true,
      },
      {
        id: "F5c",
        type: "checkboxes",
        prompt: "What concerns, if any, do you have about this benchmark design?",
        help: "Select all that apply.",
        required: true,
        exclusiveValue: "None",
        options: [
          "Real workflows are too idiosyncratic to generalize across labs",
          "Many steps cannot be verified quantitatively",
          "Only final outcomes matter; the path is irrelevant",
          "An agent might reach the expected result through a different but valid path that fixed-step scoring would unfairly penalize",
          "Data or tool access barriers make faithful execution impractical",
          "Contamination: published results may already be in the model's training data",
          "Exploratory or open-ended research may not have a single known target result",
          "An agent might find a scientifically valid solution that is better than the benchmark's reference answer",
          "None",
          { value: "Other", label: "Other", other: true },
        ],
      },
      {
        id: "F5d",
        type: "radio",
        prompt: "If an agent reaches a correct final result via a different—but scientifically valid—workflow, how should the benchmark score it?",
        required: true,
        options: ["Full credit", "Partial credit", "No credit", "It depends"],
      },
      {
        id: "F5d_detail",
        type: "text",
        prompt: "What should it depend on?",
        required: true,
        showIf: { question: "F5d", equals: "It depends" },
      },
      {
        id: "F6a",
        type: "radio",
        prompt: "Would you consider contributing one workflow from your published research or a potential future direction as a benchmark task?",
        help: "Contributors may receive acknowledgment or authorship when their contribution meets the project's authorship criteria.",
        required: true,
        options: ["Yes", "Maybe — send me details", "No"],
      },
      {
        id: "F6b",
        type: "radio",
        prompt: "May we contact you for a 30-minute follow-up interview or an expert review of sample benchmark tasks?",
        required: true,
        options: ["Yes, at the email provided", "No"],
      },
    ],
  },
  {
    id: "background",
    code: "G",
    shortTitle: "Background",
    title: "Background",
    introTitle: "Optional demographic context",
    intro: "These questions help us describe the sample in aggregate. All questions in this section are optional.",
    optional: true,
    questions: [
      {
        id: "G1",
        type: "radio",
        prompt: "Age",
        required: false,
        options: ["Under 25", "25–34", "35–44", "45–54", "55 or older", "Prefer not to say"],
      },
      {
        id: "G2",
        type: "radio",
        prompt: "Gender",
        required: false,
        options: ["Woman", "Man", "Non-binary", "Prefer to self-describe", "Prefer not to say"],
      },
      {
        id: "G2a",
        type: "text",
        prompt: "How would you like to self-describe?",
        required: false,
        showIf: { question: "G2", equals: "Prefer to self-describe" },
      },
      {
        id: "G3",
        type: "text",
        prompt: "Nationality",
        required: false,
      },
      {
        id: "G4",
        type: "textarea",
        prompt: "Is there anything important about how you do research—or how AI agents might fit into it—that we failed to ask?",
        required: false,
        rows: 5,
      },
    ],
  },
];

export const questionIndex = new Map(
  sections.flatMap((section) => section.questions.filter((question) => question.id).map((question) => [question.id, question])),
);

export const sectionIndexByQuestion = new Map(
  sections.flatMap((section, index) => section.questions.filter((question) => question.id).map((question) => [question.id, index])),
);
